### PR TITLE
release: v7.2.0

### PR DESCRIPTION
**Pull request by snprajwal**
cc @behouba

### CODE REVIEW

**Comment by snprajwal** [comment]
Okay, looks like we'll need some fixes before making the release. I'm away until Sunday, I'll do it once I'm back.

**Comment by snprajwal** [comment]
@rst0git it's interesting how I was able to create this branch through the web UI, but now it's protected - I can neither push to it, nor delete it. I meant to create the branch on my fork, but ended up creating it on this repo instead. Do we apply protection rules on non-default branches too?

**Comment by rst0git** [comment]
> Do we apply protection rules on non-default branches too?

I am not sure, we usually don't create branches in the main repository. It might be better to open another pull request and we can close this one.

@adrianreber do you have permissions to delete this branch?

**Comment by adrianreber** [comment]
Branch protection is on all branches (`*`). I did not set up the branch protection, but it does not sound bad. I removed the `release` branch now.

**Pull request closed without merging**
