### PR TITLE
test/make: drop golang version check

### PR DESCRIPTION
**Pull request by rst0git**
A check for the version of Golang was introduced with https://github.com/checkpoint-restore/go-criu/commit/740974dcb4eb8d31bb09524fb993665683a8fa99 because our test coverage requires Go version 1.20 or newer. Since we increased the minimum version to 1.20 (https://github.com/checkpoint-restore/go-criu/commit/9453d23d8ff6bed8aa5ebe560e5d1f900be149ea), this check is no longer necessary.

This pull request also fixes a problem in the CI with uploading the code coverage report to Codecov.

### CODE REVIEW

**Comment by adrianreber** [comment]
Currently we use 1.20 to run the coverage check in the GitHub Actions definition. Maybe we should also move that to 1.22. What do you think?

**Review by adrianreber — APPROVED** [review]

**Comment by rst0git** [comment]
```
[2024-07-16T07:58:12.965Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 2440s.', code='throttled')}
[2024-07-16T07:58:12.965Z] ['info'] Codecov will exit with status code 0. If you are expecting a non-zero exit code, please pass in the `-Z` flag
```

**Comment by adrianreber** [comment]
Hmm, maybe the free plan does not exist anymore or is limited. Not sure.

**Comment by rst0git** [comment]
https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage#add-the-codecov-token-to-your-repo-or-your-org

**Comment by adrianreber** [comment]
Seems to work again. No comment from codecov in the PR but maybe because the coverage did not change.

**Pull request merged**
