### PR TITLE
rpc: synchronise proto bindings with the latest version of CRIU RPC p…

### PR DESCRIPTION
**Pull request by yevzman-swe**
rpc: synchronise proto bindings with the latest version of CRIU RPC

### CODE REVIEW

**Comment by yevzman-swe** [comment]
@rst0git can you review PR?

**Comment by adrianreber** [comment]
Did you sync the changes from the CRIU release branch or criu-dev?

**Comment by yevzman-swe** [comment]
> Did you sync the changes from the CRIU release branch or criu-dev?

I sync the changes from the criu-dev branch.

**Comment by adrianreber** [comment]
> > Did you sync the changes from the CRIU release branch or criu-dev?
> 
> I sync the changes from the criu-dev branch.

Do you need those changes? I think we try to stay on the release branches of CRIU and not the criu-dev branch (if not necessary).

**Comment by snprajwal** [comment]
The master branch of criu seems to have had some changes. You can update the bindings by running `rm rpc/rpc.proto && make rpc/rpc.pb.go`

**Comment by yevzman-swe** [comment]
> > Membe
> 
> I need these changes to be able to use these flags in the runc checky runc) point/restore process. (support for flags in runc will be followed bpoint/restore process. (support for flags in runc will be pushed in runc)

**Comment by yevzman-swe** [comment]
> The master branch of criu seems to have had some changes. You can update the commit with the new bindings by running `rm rpc/rpc.proto && make rpc/rpc.pb.go`

Unfortunately, these changes are not included in the CRIU master branch

**Comment by adrianreber** [comment]
Works for me. With all the changes currently going on we will not create a release in the next couple of weeks, but I think we can merge this. @rst0git PTAL

**Comment by rst0git** [comment]
@yevzman-swe Note that to use the go-criu changes with runc, you would need to install CRIU from the `criu-dev` branch, or to wait for the next CRIU release that provides these changes.

**Review by rst0git — APPROVED** [review]

**Pull request merged**
