### PR TITLE
Update RPC protobuf definition

### PR DESCRIPTION
**Pull request by adrianreber**

### CODE REVIEW

**Comment by rst0git** [comment]
Should we add `rpc/rpc.proto` in `.gitignore`?

**Comment by adrianreber** [comment]
> Should we add `rpc/rpc.proto` in `.gitignore`?

I updated `.gitignore` to include that temporary file.

**Comment by rst0git** [comment]
LGTM

**Comment by adrianreber** [comment]
Thanks!

**Pull request merged**
